# Generated by Django 4.0.2 on 2022-03-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classbased', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyClassSample',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('classbased.classsample',),
        ),
    ]
