# Generated by Django 4.0.2 on 2022-03-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbased', '0003_usersample'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
