# Generated by Django 3.2.8 on 2022-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todovalidators', '0002_auto_20220122_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sample',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
    ]
