# Generated by Django 4.0.2 on 2022-02-23 17:48

from django.db import migrations, models
import todovalidators.models


class Migration(migrations.Migration):

    dependencies = [
        ('todovalidators', '0004_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=240, validators=[todovalidators.models.validate_title]),
        ),
    ]
